namespace Core.Tests.Integration

open System
open Binnaculum.Core.Models
open TestModels

/// <summary>
/// TSLL Broker Account Financial Snapshot data.
///
/// Contains all 71 expected broker account snapshots spanning from 2024-05-30 through 2025-10-23.
/// </summary>
module TsllBrokerSnapshots =

    /// <summary>
    /// Generate expected BrokerAccount financial snapshots with descriptions.
    ///
    /// Includes all 71 snapshots from the TSLL import test.
    /// Snapshots span from 2024-05-30 (first trade) through 2025-10-23 (last movement).
    /// </summary>
    let getBrokerAccountSnapshots
        (broker: Broker)
        (brokerAccount: BrokerAccount)
        (currency: Currency)
        : ExpectedSnapshot<BrokerFinancialSnapshot> list =
        [
          // Snapshot 1: 2024-05-30
          { Data =
              { Id = 0
                Date = DateOnly(2024, 5, 30)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 1
                RealizedGains = 0.00m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 1.00m
                Fees = 0.14m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 15.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 13.86m }
            Description = "TODO: Add description for 2024-05-30" }
          // Snapshot 2: 2024-06-07
          { Data =
              { Id = 0
                Date = DateOnly(2024, 6, 7)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 2
                RealizedGains = 13.86m
                RealizedPercentage = 100.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 1.00m
                Fees = 0.14m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 15.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 13.86m }
            Description = "TODO: Add description for 2024-06-07" }
          // Snapshot 3: 2024-10-15
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 15)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 4
                RealizedGains = 27.72m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 3.00m
                Fees = 0.41m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -471.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -474.41m }
            Description = "TODO: Add description for 2024-10-15" }
          // Snapshot 4: 2024-10-18
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 18)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 30
                RealizedGains = 27.72m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 23.00m
                Fees = 3.80m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -6906.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -6932.80m }
            Description = "TODO: Add description for 2024-10-18" }
          // Snapshot 5: 2024-10-21
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 21)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 44
                RealizedGains = 111.07m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 23.00m
                Fees = 5.59m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -7032.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -7060.59m }
            Description = "TODO: Add description for 2024-10-21" }
          // Snapshot 6: 2024-10-23
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 23)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 45
                RealizedGains = 111.07m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 24.00m
                Fees = 5.72m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -7487.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -7516.72m }
            Description = "TODO: Add description for 2024-10-23" }
          // Snapshot 7: 2024-10-24
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 24)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 60
                RealizedGains = 2194.31m
                RealizedPercentage = 933.4722m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 28.00m
                Fees = 7.93m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 271.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 235.07m }
            Description = "TODO: Add description for 2024-10-24" }
          // Snapshot 8: 2024-10-29
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 29)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 62
                RealizedGains = 2194.31m
                RealizedPercentage = 896.3697m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 30.00m
                Fees = 8.20m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 283.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 244.80m }
            Description = "TODO: Add description for 2024-10-29" }
          // Snapshot 9: 2024-10-30
          { Data =
              { Id = 0
                Date = DateOnly(2024, 10, 30)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 70
                RealizedGains = 2233.24m
                RealizedPercentage = 532.0286m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 34.00m
                Fees = 9.24m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 463.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 419.76m }
            Description = "TODO: Add description for 2024-10-30" }
          // Snapshot 10: 2024-11-01
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 1)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 78
                RealizedGains = 2372.21m
                RealizedPercentage = 378.5064m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 38.00m
                Fees = 10.27m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 675.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 626.73m }
            Description = "TODO: Add description for 2024-11-01" }
          // Snapshot 11: 2024-11-06
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 6)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 88
                RealizedGains = 1202.63m
                RealizedPercentage = 252.9782m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = 0.00m
                Commissions = 42.00m
                Fees = 11.61m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 529.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 475.39m }
            Description = "TODO: Add description for 2024-11-06" }
          // Snapshot 12: 2024-11-07
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 7)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 109
                RealizedGains = 3292.09m
                RealizedPercentage = 78.3665m
                UnrealizedGains = 18199.12m
                UnrealizedGainsPercentage = 433.2206m
                Invested = -18199.12m
                Commissions = 52.00m
                Fees = 15.11m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 4268.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4200.89m }
            Description = "TODO: Add description for 2024-11-07" }
          // Snapshot 13: 2024-11-08
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 8)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 121
                RealizedGains = 3169.24m
                RealizedPercentage = 100.5176m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -18199.12m
                Commissions = 52.00m
                Fees = 18.08m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3223.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3152.92m }
            Description = "TODO: Add description for 2024-11-08" }
          // Snapshot 14: 2024-11-20
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 20)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 133
                RealizedGains = 6324.62m
                RealizedPercentage = 144.7957m
                UnrealizedGains = 19187.76m
                UnrealizedGainsPercentage = 439.2842m
                Invested = -37386.88m
                Commissions = 61.00m
                Fees = 20.04m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 4449.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4367.96m }
            Description = "TODO: Add description for 2024-11-20" }
          // Snapshot 15: 2024-11-21
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 21)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 134
                RealizedGains = 6324.62m
                RealizedPercentage = 144.7974m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -37386.88m
                Commissions = 61.00m
                Fees = 20.09m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 4449.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4367.91m }
            Description = "TODO: Add description for 2024-11-21" }
          // Snapshot 16: 2024-11-22
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 22)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 154
                RealizedGains = 5451.26m
                RealizedPercentage = 63.5334m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -37386.88m
                Commissions = 72.00m
                Fees = 22.85m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 8675.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 8580.15m }
            Description = "TODO: Add description for 2024-11-22" }
          // Snapshot 17: 2024-11-25
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 25)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 175
                RealizedGains = 6293.25m
                RealizedPercentage = 160.5613m
                UnrealizedGains = 864.77m
                UnrealizedGainsPercentage = 22.0631m
                Invested = -38251.65m
                Commissions = 81.00m
                Fees = 25.47m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 4026.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3919.53m }
            Description = "TODO: Add description for 2024-11-25" }
          // Snapshot 18: 2024-11-26
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 26)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 198
                RealizedGains = 6553.91m
                RealizedPercentage = 78.1564m
                UnrealizedGains = 4461.72m
                UnrealizedGainsPercentage = 53.2067m
                Invested = -42713.37m
                Commissions = 92.00m
                Fees = 28.37m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 8506.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 8385.63m }
            Description = "TODO: Add description for 2024-11-26" }
          // Snapshot 19: 2024-11-27
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 27)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 199
                RealizedGains = 6553.91m
                RealizedPercentage = 78.1564m
                UnrealizedGains = 19.57m
                UnrealizedGainsPercentage = 0.2334m
                Invested = -42732.94m
                Commissions = 92.00m
                Fees = 28.37m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 8506.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 8385.63m }
            Description = "TODO: Add description for 2024-11-27" }
          // Snapshot 20: 2024-11-29
          { Data =
              { Id = 0
                Date = DateOnly(2024, 11, 29)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 223
                RealizedGains = 7181.92m
                RealizedPercentage = 221.7751m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -42732.94m
                Commissions = 103.00m
                Fees = 31.62m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3373.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3238.38m }
            Description = "TODO: Add description for 2024-11-29" }
          // Snapshot 21: 2024-12-02
          { Data =
              { Id = 0
                Date = DateOnly(2024, 12, 2)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 241
                RealizedGains = 6315.65m
                RealizedPercentage = 172.5998m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -42732.94m
                Commissions = 112.00m
                Fees = 33.87m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3805.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3659.13m }
            Description = "TODO: Add description for 2024-12-02" }
          // Snapshot 22: 2024-12-04
          { Data =
              { Id = 0
                Date = DateOnly(2024, 12, 4)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 246
                RealizedGains = 6443.09m
                RealizedPercentage = 115.0014m
                UnrealizedGains = 2450.14m
                UnrealizedGainsPercentage = 43.7320m
                Invested = -45183.08m
                Commissions = 113.00m
                Fees = 34.38m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 5750.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 5602.62m }
            Description = "TODO: Add description for 2024-12-04" }
          // Snapshot 23: 2024-12-05
          { Data =
              { Id = 0
                Date = DateOnly(2024, 12, 5)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 258
                RealizedGains = 4444.60m
                RealizedPercentage = 350.0402m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 113.00m
                Fees = 37.26m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1420.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1269.74m }
            Description = "TODO: Add description for 2024-12-05" }
          // Snapshot 24: 2024-12-11
          { Data =
              { Id = 0
                Date = DateOnly(2024, 12, 11)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 260
                RealizedGains = 5719.96m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 115.00m
                Fees = 37.51m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -764.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -916.51m }
            Description = "TODO: Add description for 2024-12-11" }
          // Snapshot 25: 2024-12-17
          { Data =
              { Id = 0
                Date = DateOnly(2024, 12, 17)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 262
                RealizedGains = 5354.71m
                RealizedPercentage = 0.0000m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 116.00m
                Fees = 37.78m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = -394.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = -547.78m }
            Description = "TODO: Add description for 2024-12-17" }
          // Snapshot 26: 2025-01-07
          { Data =
              { Id = 0
                Date = DateOnly(2025, 1, 7)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 264
                RealizedGains = 5492.15m
                RealizedPercentage = 527.1131m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 116.00m
                Fees = 38.07m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1196.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 1041.93m }
            Description = "TODO: Add description for 2025-01-07" }
          // Snapshot 27: 2025-04-07
          { Data =
              { Id = 0
                Date = DateOnly(2025, 4, 7)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 266
                RealizedGains = 5492.15m
                RealizedPercentage = 519.2737m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 118.00m
                Fees = 38.34m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1214.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1057.66m }
            Description = "TODO: Add description for 2025-04-07" }
          // Snapshot 28: 2025-04-09
          { Data =
              { Id = 0
                Date = DateOnly(2025, 4, 9)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 268
                RealizedGains = 5492.15m
                RealizedPercentage = 509.7643m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 120.00m
                Fees = 38.61m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1236.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1077.39m }
            Description = "TODO: Add description for 2025-04-09" }
          // Snapshot 29: 2025-04-24
          { Data =
              { Id = 0
                Date = DateOnly(2025, 4, 24)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 269
                RealizedGains = 5492.15m
                RealizedPercentage = 501.4517m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 121.00m
                Fees = 38.75m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1255.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1095.25m }
            Description = "TODO: Add description for 2025-04-24" }
          // Snapshot 30: 2025-04-25
          { Data =
              { Id = 0
                Date = DateOnly(2025, 4, 25)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 274
                RealizedGains = 5526.80m
                RealizedPercentage = 513.3664m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -45183.08m
                Commissions = 121.00m
                Fees = 39.42m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1237.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 1076.58m }
            Description = "TODO: Add description for 2025-04-25" }
          // Snapshot 31: 2025-04-30
          { Data =
              { Id = 0
                Date = DateOnly(2025, 4, 30)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 277
                RealizedGains = 5526.80m
                RealizedPercentage = 451.4843m
                UnrealizedGains = 1905.84m
                UnrealizedGainsPercentage = 155.6881m
                Invested = -47088.92m
                Commissions = 123.00m
                Fees = 39.86m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1387.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1224.14m }
            Description = "TODO: Add description for 2025-04-30" }
          // Snapshot 32: 2025-05-02
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 2)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 289
                RealizedGains = 5526.80m
                RealizedPercentage = 247.6187m
                UnrealizedGains = 10549.20m
                UnrealizedGainsPercentage = 472.6386m
                Invested = -57638.12m
                Commissions = 133.00m
                Fees = 42.02m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2407.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2231.98m }
            Description = "TODO: Add description for 2025-05-02" }
          // Snapshot 33: 2025-05-05
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 5)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 291
                RealizedGains = 5526.80m
                RealizedPercentage = 237.6403m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -57638.12m
                Commissions = 135.00m
                Fees = 42.30m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2503.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2325.70m }
            Description = "TODO: Add description for 2025-05-05" }
          // Snapshot 34: 2025-05-06
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 6)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 292
                RealizedGains = 5526.80m
                RealizedPercentage = 237.6413m
                UnrealizedGains = 145.04m
                UnrealizedGainsPercentage = 6.2364m
                Invested = -57783.16m
                Commissions = 135.00m
                Fees = 42.31m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2503.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2325.69m }
            Description = "TODO: Add description for 2025-05-06" }
          // Snapshot 35: 2025-05-08
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 8)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 293
                RealizedGains = 5526.80m
                RealizedPercentage = 237.6433m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -57783.16m
                Commissions = 135.00m
                Fees = 42.33m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2503.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2325.67m }
            Description = "TODO: Add description for 2025-05-08" }
          // Snapshot 36: 2025-05-09
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 9)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 308
                RealizedGains = 5069.07m
                RealizedPercentage = 822.4871m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -57783.16m
                Commissions = 135.00m
                Fees = 45.69m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 797.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 616.31m }
            Description = "TODO: Add description for 2025-05-09" }
          // Snapshot 37: 2025-05-12
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 12)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 320
                RealizedGains = 5069.07m
                RealizedPercentage = 518.3522m
                UnrealizedGains = 14834.08m
                UnrealizedGainsPercentage = 1516.9012m
                Invested = -72617.24m
                Commissions = 145.00m
                Fees = 48.08m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1171.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 977.92m }
            Description = "TODO: Add description for 2025-05-12" }
          // Snapshot 38: 2025-05-13
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 13)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 342
                RealizedGains = 4547.17m
                RealizedPercentage = 376.7239m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -72617.24m
                Commissions = 156.00m
                Fees = 50.97m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1414.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1207.03m }
            Description = "TODO: Add description for 2025-05-13" }
          // Snapshot 39: 2025-05-16
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 16)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 343
                RealizedGains = 4547.17m
                RealizedPercentage = 376.7395m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -72617.24m
                Commissions = 156.00m
                Fees = 51.02m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1414.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1206.98m }
            Description = "TODO: Add description for 2025-05-16" }
          // Snapshot 40: 2025-05-19
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 19)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 366
                RealizedGains = 4724.28m
                RealizedPercentage = 305.5907m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -72617.24m
                Commissions = 167.00m
                Fees = 54.05m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1767.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1545.95m }
            Description = "TODO: Add description for 2025-05-19" }
          // Snapshot 41: 2025-05-21
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 21)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 369
                RealizedGains = 4739.02m
                RealizedPercentage = 286.9334m
                UnrealizedGains = 1512.92m
                UnrealizedGainsPercentage = 91.6027m
                Invested = -74130.16m
                Commissions = 168.00m
                Fees = 54.39m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1874.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1651.61m }
            Description = "TODO: Add description for 2025-05-21" }
          // Snapshot 42: 2025-05-22
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 22)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 370
                RealizedGains = 4739.02m
                RealizedPercentage = 282.8455m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -74130.16m
                Commissions = 169.00m
                Fees = 54.52m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1899.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1675.48m }
            Description = "TODO: Add description for 2025-05-22" }
          // Snapshot 43: 2025-05-27
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 27)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 375
                RealizedGains = 4724.50m
                RealizedPercentage = 274.8592m
                UnrealizedGains = 1611.92m
                UnrealizedGainsPercentage = 93.7773m
                Invested = -75742.08m
                Commissions = 171.00m
                Fees = 55.12m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 1945.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1718.88m }
            Description = "TODO: Add description for 2025-05-27" }
          // Snapshot 44: 2025-05-29
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 29)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 399
                RealizedGains = 4091.35m
                RealizedPercentage = 208.9823m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -75742.08m
                Commissions = 181.00m
                Fees = 58.25m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2197.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 1957.75m }
            Description = "TODO: Add description for 2025-05-29" }
          // Snapshot 45: 2025-05-30
          { Data =
              { Id = 0
                Date = DateOnly(2025, 5, 30)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 403
                RealizedGains = 4135.83m
                RealizedPercentage = 205.8415m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -75742.08m
                Commissions = 183.00m
                Fees = 58.77m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2251.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2009.23m }
            Description = "TODO: Add description for 2025-05-30" }
          // Snapshot 46: 2025-06-02
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 2)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 404
                RealizedGains = 4135.83m
                RealizedPercentage = 201.3451m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -75742.08m
                Commissions = 184.00m
                Fees = 58.90m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2297.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2054.10m }
            Description = "TODO: Add description for 2025-06-02" }
          // Snapshot 47: 2025-06-03
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 3)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 407
                RealizedGains = 4111.31m
                RealizedPercentage = 200.8741m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -75742.08m
                Commissions = 185.00m
                Fees = 59.29m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2291.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2046.71m }
            Description = "TODO: Add description for 2025-06-03" }
          // Snapshot 48: 2025-06-10
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 10)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 408
                RealizedGains = 4111.31m
                RealizedPercentage = 200.8819m
                UnrealizedGains = 1199.92m
                UnrealizedGainsPercentage = 58.6291m
                Invested = -76942.00m
                Commissions = 185.00m
                Fees = 59.37m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2291.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2046.63m }
            Description = "TODO: Add description for 2025-06-10" }
          // Snapshot 49: 2025-06-12
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 12)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 421
                RealizedGains = 6485.92m
                RealizedPercentage = 319.1968m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -76942.00m
                Commissions = 185.00m
                Fees = 61.05m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2278.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 2031.95m }
            Description = "TODO: Add description for 2025-06-12" }
          // Snapshot 50: 2025-06-13
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 13)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 436
                RealizedGains = 6485.92m
                RealizedPercentage = 236.5415m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -76942.00m
                Commissions = 196.00m
                Fees = 63.02m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3001.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2741.98m }
            Description = "TODO: Add description for 2025-06-13" }
          // Snapshot 51: 2025-06-17
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 17)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 450
                RealizedGains = 7032.26m
                RealizedPercentage = 270.4549m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -76942.00m
                Commissions = 196.00m
                Fees = 64.84m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 2861.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 2600.16m }
            Description = "TODO: Add description for 2025-06-17" }
          // Snapshot 52: 2025-06-18
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 18)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 467
                RealizedGains = 7042.00m
                RealizedPercentage = 207.0586m
                UnrealizedGains = 1248.92m
                UnrealizedGainsPercentage = 36.7225m
                Invested = -78190.92m
                Commissions = 206.00m
                Fees = 67.03m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3674.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3400.97m }
            Description = "TODO: Add description for 2025-06-18" }
          // Snapshot 53: 2025-06-20
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 20)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 469
                RealizedGains = 7042.00m
                RealizedPercentage = 207.0604m
                UnrealizedGains = 383.31m
                UnrealizedGainsPercentage = 11.2707m
                Invested = -78574.23m
                Commissions = 206.00m
                Fees = 67.06m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3674.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3400.94m }
            Description = "TODO: Add description for 2025-06-20" }
          // Snapshot 54: 2025-06-23
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 23)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 470
                RealizedGains = 7042.00m
                RealizedPercentage = 207.0622m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -78574.23m
                Commissions = 206.00m
                Fees = 67.09m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 3674.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3400.91m }
            Description = "TODO: Add description for 2025-06-23" }
          // Snapshot 55: 2025-06-25
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 25)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 503
                RealizedGains = 7118.07m
                RealizedPercentage = 118.8814m
                UnrealizedGains = 2471.84m
                UnrealizedGainsPercentage = 41.2831m
                Invested = -81046.07m
                Commissions = 218.00m
                Fees = 71.46m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 6277.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 5987.54m }
            Description = "TODO: Add description for 2025-06-25" }
          // Snapshot 56: 2025-06-27
          { Data =
              { Id = 0
                Date = DateOnly(2025, 6, 27)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 521
                RealizedGains = 8382.61m
                RealizedPercentage = 213.4772m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -81046.07m
                Commissions = 218.00m
                Fees = 75.30m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 0.00m
                OptionsIncome = 4220.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3926.70m }
            Description = "TODO: Add description for 2025-06-27" }
          // Snapshot 57: 2025-07-01
          { Data =
              { Id = 0
                Date = DateOnly(2025, 7, 1)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 525
                RealizedGains = 8382.61m
                RealizedPercentage = 207.4405m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -81046.07m
                Commissions = 218.00m
                Fees = 75.30m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4220.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 4040.97m }
            Description = "TODO: Add description for 2025-07-01" }
          // Snapshot 58: 2025-07-08
          { Data =
              { Id = 0
                Date = DateOnly(2025, 7, 8)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 528
                RealizedGains = 8382.61m
                RealizedPercentage = 205.4179m
                UnrealizedGains = 1047.92m
                UnrealizedGainsPercentage = 25.6795m
                Invested = -82093.99m
                Commissions = 219.00m
                Fees = 75.51m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4261.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4080.76m }
            Description = "TODO: Add description for 2025-07-08" }
          // Snapshot 59: 2025-07-10
          { Data =
              { Id = 0
                Date = DateOnly(2025, 7, 10)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 530
                RealizedGains = 8369.35m
                RealizedPercentage = 200.0562m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 220.00m
                Fees = 75.77m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4365.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4183.50m }
            Description = "TODO: Add description for 2025-07-10" }
          // Snapshot 60: 2025-07-23
          { Data =
              { Id = 0
                Date = DateOnly(2025, 7, 23)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 532
                RealizedGains = 8245.09m
                RealizedPercentage = 211.2355m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 220.00m
                Fees = 76.00m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4085.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3903.27m }
            Description = "TODO: Add description for 2025-07-23" }
          // Snapshot 61: 2025-07-29
          { Data =
              { Id = 0
                Date = DateOnly(2025, 7, 29)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 542
                RealizedGains = 8245.09m
                RealizedPercentage = 195.9855m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 230.00m
                Fees = 77.28m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4400.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4206.99m }
            Description = "TODO: Add description for 2025-07-29" }
          // Snapshot 62: 2025-08-06
          { Data =
              { Id = 0
                Date = DateOnly(2025, 8, 6)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 552
                RealizedGains = 8387.58m
                RealizedPercentage = 207.3178m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 230.00m
                Fees = 78.51m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4240.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 4045.76m }
            Description = "TODO: Add description for 2025-08-06" }
          // Snapshot 63: 2025-09-02
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 2)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 553
                RealizedGains = 8387.58m
                RealizedPercentage = 203.8472m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 231.00m
                Fees = 78.63m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4310.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4114.64m }
            Description = "TODO: Add description for 2025-09-02" }
          // Snapshot 64: 2025-09-03
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 3)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 554
                RealizedGains = 8405.34m
                RealizedPercentage = 206.8487m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -82093.99m
                Commissions = 231.00m
                Fees = 78.75m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4259.00m
                OtherIncome = 0.00m
                OpenTrades = false
                NetCashFlow = 4063.52m }
            Description = "TODO: Add description for 2025-09-03" }
          // Snapshot 65: 2025-09-05
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 5)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 556
                RealizedGains = 8405.34m
                RealizedPercentage = 205.0923m
                UnrealizedGains = 1332.92m
                UnrealizedGainsPercentage = 32.5236m
                Invested = -83426.91m
                Commissions = 232.00m
                Fees = 78.95m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4295.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4098.32m }
            Description = "TODO: Add description for 2025-09-05" }
          // Snapshot 66: 2025-09-08
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 8)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 557
                RealizedGains = 8405.34m
                RealizedPercentage = 204.0527m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 233.00m
                Fees = 79.07m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4317.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4119.20m }
            Description = "TODO: Add description for 2025-09-08" }
          // Snapshot 67: 2025-09-11
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 11)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 559
                RealizedGains = 8388.10m
                RealizedPercentage = 201.6874m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 234.00m
                Fees = 79.31m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4358.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4158.96m }
            Description = "TODO: Add description for 2025-09-11" }
          // Snapshot 68: 2025-09-12
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 12)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 560
                RealizedGains = 8408.98m
                RealizedPercentage = 202.1895m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 234.00m
                Fees = 79.31m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4358.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4158.96m }
            Description = "TODO: Add description for 2025-09-12" }
          // Snapshot 69: 2025-09-17
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 17)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 562
                RealizedGains = 8068.74m
                RealizedPercentage = 193.8334m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 235.00m
                Fees = 79.55m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 114.27m
                OptionsIncome = 4363.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4162.72m }
            Description = "TODO: Add description for 2025-09-17" }
          // Snapshot 70: 2025-09-30
          { Data =
              { Id = 0
                Date = DateOnly(2025, 9, 30)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 564
                RealizedGains = 8068.74m
                RealizedPercentage = 193.4806m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 235.00m
                Fees = 79.55m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 121.86m
                OptionsIncome = 4363.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 4170.31m }
            Description = "TODO: Add description for 2025-09-30" }
          // Snapshot 71: 2025-10-23
          { Data =
              { Id = 0
                Date = DateOnly(2025, 10, 23)
                Broker = Some broker
                BrokerAccount = Some brokerAccount
                Currency = currency
                MovementCounter = 566
                RealizedGains = 8011.50m
                RealizedPercentage = 217.8761m
                UnrealizedGains = 0.00m
                UnrealizedGainsPercentage = 0.0000m
                Invested = -83426.91m
                Commissions = 235.00m
                Fees = 79.77m
                Deposited = 0.00m
                Withdrawn = 0.00m
                DividendsReceived = 121.86m
                OptionsIncome = 3870.00m
                OtherIncome = 0.00m
                OpenTrades = true
                NetCashFlow = 3677.09m }
            Description = "TODO: Add description for 2025-10-23" }

          ]
