//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binnaculum.Resources.Languages; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class AppResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Binnaculum.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Change selection:.
    /// </summary>
    internal static string AccountCreator_Change_Selection {
        get {
            return ResourceManager.GetString("AccountCreator_Change_Selection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Create a bank.
    /// </summary>
    internal static string AccountCreator_Create_Bank {
        get {
            return ResourceManager.GetString("AccountCreator_Create_Bank", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Type the name.
    /// </summary>
    internal static string AccountCreator_Create_Bank_And_Placeholder {
        get {
            return ResourceManager.GetString("AccountCreator_Create_Bank_And_Placeholder", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Create a broker.
    /// </summary>
    internal static string AccountCreator_Create_Broker {
        get {
            return ResourceManager.GetString("AccountCreator_Create_Broker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Creating account for {0} bank:.
    /// </summary>
    internal static string AccountCreator_Creating_Account_For_Bank {
        get {
            return ResourceManager.GetString("AccountCreator_Creating_Account_For_Bank", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Creating account for {0} broker:.
    /// </summary>
    internal static string AccountCreator_Creating_Account_For_Broker {
        get {
            return ResourceManager.GetString("AccountCreator_Creating_Account_For_Broker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select a bank:.
    /// </summary>
    internal static string AccountCreator_Select_Bank {
        get {
            return ResourceManager.GetString("AccountCreator_Select_Bank", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select a broker:.
    /// </summary>
    internal static string AccountCreator_Select_Broker {
        get {
            return ResourceManager.GetString("AccountCreator_Select_Broker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Add movement.
    /// </summary>
    internal static string Account_Card_Add_Movement {
        get {
            return ResourceManager.GetString("Account_Card_Add_Movement", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Balance.
    /// </summary>
    internal static string BankMovementType_Balance {
        get {
            return ResourceManager.GetString("BankMovementType_Balance", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fees.
    /// </summary>
    internal static string BankMovementType_Fees {
        get {
            return ResourceManager.GetString("BankMovementType_Fees", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Interests.
    /// </summary>
    internal static string BankMovementType_Interest {
        get {
            return ResourceManager.GetString("BankMovementType_Interest", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to From file.
    /// </summary>
    internal static string BrokerMovementCreator_How_To_File {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_How_To_File", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Manually.
    /// </summary>
    internal static string BrokerMovementCreator_How_To_Manual {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_How_To_Manual", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to How to create.
    /// </summary>
    internal static string BrokerMovementCreator_How_To_Title {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_How_To_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import completed successfully.
    /// </summary>
    internal static string BrokerMovementCreator_ImportComplete {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_ImportComplete", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import failed.
    /// </summary>
    internal static string BrokerMovementCreator_ImportError {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_ImportError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Importing transactions....
    /// </summary>
    internal static string BrokerMovementCreator_ImportProgress {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_ImportProgress", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select File.
    /// </summary>
    internal static string BrokerMovementCreator_SelectFile {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_SelectFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select a broker statement file to import transactions.
    /// </summary>
    internal static string BrokerMovementCreator_SelectFileHint {
        get {
            return ResourceManager.GetString("BrokerMovementCreator_SelectFileHint", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to UAE dirham.
    /// </summary>
    internal static string Currency_AED {
        get {
            return ResourceManager.GetString("Currency_AED", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Afghan afghani.
    /// </summary>
    internal static string Currency_AFN {
        get {
            return ResourceManager.GetString("Currency_AFN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Albanian lek.
    /// </summary>
    internal static string Currency_ALL {
        get {
            return ResourceManager.GetString("Currency_ALL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Armenian dram.
    /// </summary>
    internal static string Currency_AMD {
        get {
            return ResourceManager.GetString("Currency_AMD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Netherlands Antillean gulden.
    /// </summary>
    internal static string Currency_ANG {
        get {
            return ResourceManager.GetString("Currency_ANG", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Angolan kwanza.
    /// </summary>
    internal static string Currency_AOA {
        get {
            return ResourceManager.GetString("Currency_AOA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Argentine peso.
    /// </summary>
    internal static string Currency_ARS {
        get {
            return ResourceManager.GetString("Currency_ARS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Australian dollar.
    /// </summary>
    internal static string Currency_AUD {
        get {
            return ResourceManager.GetString("Currency_AUD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Aruban florin.
    /// </summary>
    internal static string Currency_AWG {
        get {
            return ResourceManager.GetString("Currency_AWG", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Azerbaijani manat.
    /// </summary>
    internal static string Currency_AZN {
        get {
            return ResourceManager.GetString("Currency_AZN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bosnia and Herzegovina konvertibilna marka.
    /// </summary>
    internal static string Currency_BAM {
        get {
            return ResourceManager.GetString("Currency_BAM", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Barbadian dollar.
    /// </summary>
    internal static string Currency_BBD {
        get {
            return ResourceManager.GetString("Currency_BBD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bangladeshi taka.
    /// </summary>
    internal static string Currency_BDT {
        get {
            return ResourceManager.GetString("Currency_BDT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bulgarian lev.
    /// </summary>
    internal static string Currency_BGN {
        get {
            return ResourceManager.GetString("Currency_BGN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bahraini dinar.
    /// </summary>
    internal static string Currency_BHD {
        get {
            return ResourceManager.GetString("Currency_BHD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Burundi franc.
    /// </summary>
    internal static string Currency_BIF {
        get {
            return ResourceManager.GetString("Currency_BIF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bermudian dollar.
    /// </summary>
    internal static string Currency_BMD {
        get {
            return ResourceManager.GetString("Currency_BMD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Brunei dollar.
    /// </summary>
    internal static string Currency_BND {
        get {
            return ResourceManager.GetString("Currency_BND", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bolivian boliviano.
    /// </summary>
    internal static string Currency_BOB {
        get {
            return ResourceManager.GetString("Currency_BOB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Brazilian real.
    /// </summary>
    internal static string Currency_BRL {
        get {
            return ResourceManager.GetString("Currency_BRL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bahamian dollar.
    /// </summary>
    internal static string Currency_BSD {
        get {
            return ResourceManager.GetString("Currency_BSD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bhutanese ngultrum.
    /// </summary>
    internal static string Currency_BTN {
        get {
            return ResourceManager.GetString("Currency_BTN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Botswana pula.
    /// </summary>
    internal static string Currency_BWP {
        get {
            return ResourceManager.GetString("Currency_BWP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Belarusian ruble.
    /// </summary>
    internal static string Currency_BYR {
        get {
            return ResourceManager.GetString("Currency_BYR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Belize dollar.
    /// </summary>
    internal static string Currency_BZD {
        get {
            return ResourceManager.GetString("Currency_BZD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Canadian dollar.
    /// </summary>
    internal static string Currency_CAD {
        get {
            return ResourceManager.GetString("Currency_CAD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Congolese franc.
    /// </summary>
    internal static string Currency_CDF {
        get {
            return ResourceManager.GetString("Currency_CDF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Swiss franc.
    /// </summary>
    internal static string Currency_CHF {
        get {
            return ResourceManager.GetString("Currency_CHF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Chilean peso.
    /// </summary>
    internal static string Currency_CLP {
        get {
            return ResourceManager.GetString("Currency_CLP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Chinese yuan renminbi.
    /// </summary>
    internal static string Currency_CNY {
        get {
            return ResourceManager.GetString("Currency_CNY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Colombian peso.
    /// </summary>
    internal static string Currency_COP {
        get {
            return ResourceManager.GetString("Currency_COP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Costa Rican colon.
    /// </summary>
    internal static string Currency_CRC {
        get {
            return ResourceManager.GetString("Currency_CRC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cuban peso.
    /// </summary>
    internal static string Currency_CUC {
        get {
            return ResourceManager.GetString("Currency_CUC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cape Verdean escudo.
    /// </summary>
    internal static string Currency_CVE {
        get {
            return ResourceManager.GetString("Currency_CVE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Czech koruna.
    /// </summary>
    internal static string Currency_CZK {
        get {
            return ResourceManager.GetString("Currency_CZK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Djiboutian franc.
    /// </summary>
    internal static string Currency_DJF {
        get {
            return ResourceManager.GetString("Currency_DJF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Danish krone.
    /// </summary>
    internal static string Currency_DKK {
        get {
            return ResourceManager.GetString("Currency_DKK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dominican peso.
    /// </summary>
    internal static string Currency_DOP {
        get {
            return ResourceManager.GetString("Currency_DOP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Algerian dinar.
    /// </summary>
    internal static string Currency_DZD {
        get {
            return ResourceManager.GetString("Currency_DZD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Estonian kroon.
    /// </summary>
    internal static string Currency_EEK {
        get {
            return ResourceManager.GetString("Currency_EEK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Egyptian pound.
    /// </summary>
    internal static string Currency_EGP {
        get {
            return ResourceManager.GetString("Currency_EGP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Eritrean nakfa.
    /// </summary>
    internal static string Currency_ERN {
        get {
            return ResourceManager.GetString("Currency_ERN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ethiopian birr.
    /// </summary>
    internal static string Currency_ETB {
        get {
            return ResourceManager.GetString("Currency_ETB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to European Euro.
    /// </summary>
    internal static string Currency_EUR {
        get {
            return ResourceManager.GetString("Currency_EUR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fijian dollar.
    /// </summary>
    internal static string Currency_FJD {
        get {
            return ResourceManager.GetString("Currency_FJD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Falkland Islands pound.
    /// </summary>
    internal static string Currency_FKP {
        get {
            return ResourceManager.GetString("Currency_FKP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to British pound.
    /// </summary>
    internal static string Currency_GBP {
        get {
            return ResourceManager.GetString("Currency_GBP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Georgian lari.
    /// </summary>
    internal static string Currency_GEL {
        get {
            return ResourceManager.GetString("Currency_GEL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ghanaian cedi.
    /// </summary>
    internal static string Currency_GHS {
        get {
            return ResourceManager.GetString("Currency_GHS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gibraltar pound.
    /// </summary>
    internal static string Currency_GIP {
        get {
            return ResourceManager.GetString("Currency_GIP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gambian dalasi.
    /// </summary>
    internal static string Currency_GMD {
        get {
            return ResourceManager.GetString("Currency_GMD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Guinean franc.
    /// </summary>
    internal static string Currency_GNF {
        get {
            return ResourceManager.GetString("Currency_GNF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Central African CFA franc.
    /// </summary>
    internal static string Currency_GQE {
        get {
            return ResourceManager.GetString("Currency_GQE", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Guatemalan quetzal.
    /// </summary>
    internal static string Currency_GTQ {
        get {
            return ResourceManager.GetString("Currency_GTQ", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Guyanese dollar.
    /// </summary>
    internal static string Currency_GYD {
        get {
            return ResourceManager.GetString("Currency_GYD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hong Kong dollar.
    /// </summary>
    internal static string Currency_HKD {
        get {
            return ResourceManager.GetString("Currency_HKD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Honduran lempira.
    /// </summary>
    internal static string Currency_HNL {
        get {
            return ResourceManager.GetString("Currency_HNL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Croatian kuna.
    /// </summary>
    internal static string Currency_HRK {
        get {
            return ResourceManager.GetString("Currency_HRK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Haitian gourde.
    /// </summary>
    internal static string Currency_HTG {
        get {
            return ResourceManager.GetString("Currency_HTG", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hungarian forint.
    /// </summary>
    internal static string Currency_HUF {
        get {
            return ResourceManager.GetString("Currency_HUF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Indonesian rupiah.
    /// </summary>
    internal static string Currency_IDR {
        get {
            return ResourceManager.GetString("Currency_IDR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Israeli new sheqel.
    /// </summary>
    internal static string Currency_ILS {
        get {
            return ResourceManager.GetString("Currency_ILS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Indian rupee.
    /// </summary>
    internal static string Currency_INR {
        get {
            return ResourceManager.GetString("Currency_INR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Iraqi dinar.
    /// </summary>
    internal static string Currency_IQD {
        get {
            return ResourceManager.GetString("Currency_IQD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Iranian rial.
    /// </summary>
    internal static string Currency_IRR {
        get {
            return ResourceManager.GetString("Currency_IRR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Icelandic króna.
    /// </summary>
    internal static string Currency_ISK {
        get {
            return ResourceManager.GetString("Currency_ISK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Jamaican dollar.
    /// </summary>
    internal static string Currency_JMD {
        get {
            return ResourceManager.GetString("Currency_JMD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Jordanian dinar.
    /// </summary>
    internal static string Currency_JOD {
        get {
            return ResourceManager.GetString("Currency_JOD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Japanese yen.
    /// </summary>
    internal static string Currency_JPY {
        get {
            return ResourceManager.GetString("Currency_JPY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kenyan shilling.
    /// </summary>
    internal static string Currency_KES {
        get {
            return ResourceManager.GetString("Currency_KES", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kyrgyzstani som.
    /// </summary>
    internal static string Currency_KGS {
        get {
            return ResourceManager.GetString("Currency_KGS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cambodian riel.
    /// </summary>
    internal static string Currency_KHR {
        get {
            return ResourceManager.GetString("Currency_KHR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Comorian franc.
    /// </summary>
    internal static string Currency_KMF {
        get {
            return ResourceManager.GetString("Currency_KMF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to North Korean won.
    /// </summary>
    internal static string Currency_KPW {
        get {
            return ResourceManager.GetString("Currency_KPW", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to South Korean won.
    /// </summary>
    internal static string Currency_KRW {
        get {
            return ResourceManager.GetString("Currency_KRW", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kuwaiti dinar.
    /// </summary>
    internal static string Currency_KWD {
        get {
            return ResourceManager.GetString("Currency_KWD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cayman Islands dollar.
    /// </summary>
    internal static string Currency_KYD {
        get {
            return ResourceManager.GetString("Currency_KYD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kazakhstani tenge.
    /// </summary>
    internal static string Currency_KZT {
        get {
            return ResourceManager.GetString("Currency_KZT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lao kip.
    /// </summary>
    internal static string Currency_LAK {
        get {
            return ResourceManager.GetString("Currency_LAK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lebanese lira.
    /// </summary>
    internal static string Currency_LBP {
        get {
            return ResourceManager.GetString("Currency_LBP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sri Lankan rupee.
    /// </summary>
    internal static string Currency_LKR {
        get {
            return ResourceManager.GetString("Currency_LKR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Liberian dollar.
    /// </summary>
    internal static string Currency_LRD {
        get {
            return ResourceManager.GetString("Currency_LRD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lesotho loti.
    /// </summary>
    internal static string Currency_LSL {
        get {
            return ResourceManager.GetString("Currency_LSL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lithuanian litas.
    /// </summary>
    internal static string Currency_LTL {
        get {
            return ResourceManager.GetString("Currency_LTL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Latvian lats.
    /// </summary>
    internal static string Currency_LVL {
        get {
            return ResourceManager.GetString("Currency_LVL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Libyan dinar.
    /// </summary>
    internal static string Currency_LYD {
        get {
            return ResourceManager.GetString("Currency_LYD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Moroccan dirham.
    /// </summary>
    internal static string Currency_MAD {
        get {
            return ResourceManager.GetString("Currency_MAD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Moldovan leu.
    /// </summary>
    internal static string Currency_MDL {
        get {
            return ResourceManager.GetString("Currency_MDL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Malagasy ariary.
    /// </summary>
    internal static string Currency_MGA {
        get {
            return ResourceManager.GetString("Currency_MGA", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Macedonian denar.
    /// </summary>
    internal static string Currency_MKD {
        get {
            return ResourceManager.GetString("Currency_MKD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Myanma kyat.
    /// </summary>
    internal static string Currency_MMK {
        get {
            return ResourceManager.GetString("Currency_MMK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mongolian tugrik.
    /// </summary>
    internal static string Currency_MNT {
        get {
            return ResourceManager.GetString("Currency_MNT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Macanese pataca.
    /// </summary>
    internal static string Currency_MOP {
        get {
            return ResourceManager.GetString("Currency_MOP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mauritanian ouguiya.
    /// </summary>
    internal static string Currency_MRO {
        get {
            return ResourceManager.GetString("Currency_MRO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mauritian rupee.
    /// </summary>
    internal static string Currency_MUR {
        get {
            return ResourceManager.GetString("Currency_MUR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Maldivian rufiyaa.
    /// </summary>
    internal static string Currency_MVR {
        get {
            return ResourceManager.GetString("Currency_MVR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Malawian kwacha.
    /// </summary>
    internal static string Currency_MWK {
        get {
            return ResourceManager.GetString("Currency_MWK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mexican peso.
    /// </summary>
    internal static string Currency_MXN {
        get {
            return ResourceManager.GetString("Currency_MXN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Malaysian ringgit.
    /// </summary>
    internal static string Currency_MYR {
        get {
            return ResourceManager.GetString("Currency_MYR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mozambican metical.
    /// </summary>
    internal static string Currency_MZM {
        get {
            return ResourceManager.GetString("Currency_MZM", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Namibian dollar.
    /// </summary>
    internal static string Currency_NAD {
        get {
            return ResourceManager.GetString("Currency_NAD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Nigerian naira.
    /// </summary>
    internal static string Currency_NGN {
        get {
            return ResourceManager.GetString("Currency_NGN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Nicaraguan córdoba.
    /// </summary>
    internal static string Currency_NIO {
        get {
            return ResourceManager.GetString("Currency_NIO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Norwegian krone.
    /// </summary>
    internal static string Currency_NOK {
        get {
            return ResourceManager.GetString("Currency_NOK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Nepalese rupee.
    /// </summary>
    internal static string Currency_NPR {
        get {
            return ResourceManager.GetString("Currency_NPR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to New Zealand dollar.
    /// </summary>
    internal static string Currency_NZD {
        get {
            return ResourceManager.GetString("Currency_NZD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Omani rial.
    /// </summary>
    internal static string Currency_OMR {
        get {
            return ResourceManager.GetString("Currency_OMR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Panamanian balboa.
    /// </summary>
    internal static string Currency_PAB {
        get {
            return ResourceManager.GetString("Currency_PAB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Peruvian nuevo sol.
    /// </summary>
    internal static string Currency_PEN {
        get {
            return ResourceManager.GetString("Currency_PEN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Papua New Guinean kina.
    /// </summary>
    internal static string Currency_PGK {
        get {
            return ResourceManager.GetString("Currency_PGK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Philippine peso.
    /// </summary>
    internal static string Currency_PHP {
        get {
            return ResourceManager.GetString("Currency_PHP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Pakistani rupee.
    /// </summary>
    internal static string Currency_PKR {
        get {
            return ResourceManager.GetString("Currency_PKR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Polish zloty.
    /// </summary>
    internal static string Currency_PLN {
        get {
            return ResourceManager.GetString("Currency_PLN", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Paraguayan guarani.
    /// </summary>
    internal static string Currency_PYG {
        get {
            return ResourceManager.GetString("Currency_PYG", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Qatari riyal.
    /// </summary>
    internal static string Currency_QAR {
        get {
            return ResourceManager.GetString("Currency_QAR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Romanian leu.
    /// </summary>
    internal static string Currency_RON {
        get {
            return ResourceManager.GetString("Currency_RON", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Serbian dinar.
    /// </summary>
    internal static string Currency_RSD {
        get {
            return ResourceManager.GetString("Currency_RSD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Russian ruble.
    /// </summary>
    internal static string Currency_RUB {
        get {
            return ResourceManager.GetString("Currency_RUB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saudi riyal.
    /// </summary>
    internal static string Currency_SAR {
        get {
            return ResourceManager.GetString("Currency_SAR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Solomon Islands dollar.
    /// </summary>
    internal static string Currency_SBD {
        get {
            return ResourceManager.GetString("Currency_SBD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Seychellois rupee.
    /// </summary>
    internal static string Currency_SCR {
        get {
            return ResourceManager.GetString("Currency_SCR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sudanese pound.
    /// </summary>
    internal static string Currency_SDG {
        get {
            return ResourceManager.GetString("Currency_SDG", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Swedish krona.
    /// </summary>
    internal static string Currency_SEK {
        get {
            return ResourceManager.GetString("Currency_SEK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Singapore dollar.
    /// </summary>
    internal static string Currency_SGD {
        get {
            return ResourceManager.GetString("Currency_SGD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saint Helena pound.
    /// </summary>
    internal static string Currency_SHP {
        get {
            return ResourceManager.GetString("Currency_SHP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sierra Leonean leone.
    /// </summary>
    internal static string Currency_SLL {
        get {
            return ResourceManager.GetString("Currency_SLL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Somali shilling.
    /// </summary>
    internal static string Currency_SOS {
        get {
            return ResourceManager.GetString("Currency_SOS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Surinamese dollar.
    /// </summary>
    internal static string Currency_SRD {
        get {
            return ResourceManager.GetString("Currency_SRD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Syrian pound.
    /// </summary>
    internal static string Currency_SYP {
        get {
            return ResourceManager.GetString("Currency_SYP", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Swazi lilangeni.
    /// </summary>
    internal static string Currency_SZL {
        get {
            return ResourceManager.GetString("Currency_SZL", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Thai baht.
    /// </summary>
    internal static string Currency_THB {
        get {
            return ResourceManager.GetString("Currency_THB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tajikistani somoni.
    /// </summary>
    internal static string Currency_TJS {
        get {
            return ResourceManager.GetString("Currency_TJS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Turkmen manat.
    /// </summary>
    internal static string Currency_TMT {
        get {
            return ResourceManager.GetString("Currency_TMT", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tunisian dinar.
    /// </summary>
    internal static string Currency_TND {
        get {
            return ResourceManager.GetString("Currency_TND", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Turkish new lira.
    /// </summary>
    internal static string Currency_TRY {
        get {
            return ResourceManager.GetString("Currency_TRY", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Trinidad and Tobago dollar.
    /// </summary>
    internal static string Currency_TTD {
        get {
            return ResourceManager.GetString("Currency_TTD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to New Taiwan dollar.
    /// </summary>
    internal static string Currency_TWD {
        get {
            return ResourceManager.GetString("Currency_TWD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tanzanian shilling.
    /// </summary>
    internal static string Currency_TZS {
        get {
            return ResourceManager.GetString("Currency_TZS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ukrainian hryvnia.
    /// </summary>
    internal static string Currency_UAH {
        get {
            return ResourceManager.GetString("Currency_UAH", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ugandan shilling.
    /// </summary>
    internal static string Currency_UGX {
        get {
            return ResourceManager.GetString("Currency_UGX", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to United States dollar.
    /// </summary>
    internal static string Currency_USD {
        get {
            return ResourceManager.GetString("Currency_USD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Uruguayan peso.
    /// </summary>
    internal static string Currency_UYU {
        get {
            return ResourceManager.GetString("Currency_UYU", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Uzbekistani som.
    /// </summary>
    internal static string Currency_UZS {
        get {
            return ResourceManager.GetString("Currency_UZS", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Venezuelan bolivar.
    /// </summary>
    internal static string Currency_VEB {
        get {
            return ResourceManager.GetString("Currency_VEB", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Vietnamese dong.
    /// </summary>
    internal static string Currency_VND {
        get {
            return ResourceManager.GetString("Currency_VND", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Vanuatu vatu.
    /// </summary>
    internal static string Currency_VUV {
        get {
            return ResourceManager.GetString("Currency_VUV", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Samoan tala.
    /// </summary>
    internal static string Currency_WST {
        get {
            return ResourceManager.GetString("Currency_WST", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Central African CFA franc.
    /// </summary>
    internal static string Currency_XAF {
        get {
            return ResourceManager.GetString("Currency_XAF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to East Caribbean dollar.
    /// </summary>
    internal static string Currency_XCD {
        get {
            return ResourceManager.GetString("Currency_XCD", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Special Drawing Rights.
    /// </summary>
    internal static string Currency_XDR {
        get {
            return ResourceManager.GetString("Currency_XDR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to West African CFA franc.
    /// </summary>
    internal static string Currency_XOF {
        get {
            return ResourceManager.GetString("Currency_XOF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to CFP franc.
    /// </summary>
    internal static string Currency_XPF {
        get {
            return ResourceManager.GetString("Currency_XPF", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Yemeni rial.
    /// </summary>
    internal static string Currency_YER {
        get {
            return ResourceManager.GetString("Currency_YER", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to South African rand.
    /// </summary>
    internal static string Currency_ZAR {
        get {
            return ResourceManager.GetString("Currency_ZAR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Zambian kwacha.
    /// </summary>
    internal static string Currency_ZMK {
        get {
            return ResourceManager.GetString("Currency_ZMK", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Zimbabwean dollar.
    /// </summary>
    internal static string Currency_ZWR {
        get {
            return ResourceManager.GetString("Currency_ZWR", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select an image.
    /// </summary>
    internal static string FilePicker_Select_Image {
        get {
            return ResourceManager.GetString("FilePicker_Select_Image", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cancel.
    /// </summary>
    internal static string Global_Button_Cancel {
        get {
            return ResourceManager.GetString("Global_Button_Cancel", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Confirm.
    /// </summary>
    internal static string Global_Button_Confirm {
        get {
            return ResourceManager.GetString("Global_Button_Confirm", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Discard.
    /// </summary>
    internal static string Global_Button_Discard {
        get {
            return ResourceManager.GetString("Global_Button_Discard", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ok.
    /// </summary>
    internal static string Global_Button_Ok {
        get {
            return ResourceManager.GetString("Global_Button_Ok", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Save.
    /// </summary>
    internal static string Global_Button_Save {
        get {
            return ResourceManager.GetString("Global_Button_Save", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Error.
    /// </summary>
    internal static string Global_Error_Title {
        get {
            return ResourceManager.GetString("Global_Error_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Success.
    /// </summary>
    internal static string Global_Success_Title {
        get {
            return ResourceManager.GetString("Global_Success_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Bank.
    /// </summary>
    internal static string Global_Title_Bank {
        get {
            return ResourceManager.GetString("Global_Title_Bank", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Broker.
    /// </summary>
    internal static string Global_Title_Broker {
        get {
            return ResourceManager.GetString("Global_Title_Broker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating snapshots: {0} of {1} ({2}).
    /// </summary>
    internal static string Import_CalculatingSnapshots {
        get {
            return ResourceManager.GetString("Import_CalculatingSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating snapshots....
    /// </summary>
    internal static string Import_CalculatingSnapshots_Generic {
        get {
            return ResourceManager.GetString("Import_CalculatingSnapshots_Generic", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import cancelled.
    /// </summary>
    internal static string Import_Cancelled {
        get {
            return ResourceManager.GetString("Import_Cancelled", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Analyzing dates in {0}....
    /// </summary>
    internal static string Import_Chunked_AnalyzingDates {
        get {
            return ResourceManager.GetString("Import_Chunked_AnalyzingDates", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating {0} ({1} of {2}).
    /// </summary>
    internal static string Import_Chunked_CalculatingSnapshots {
        get {
            return ResourceManager.GetString("Import_Chunked_CalculatingSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Week of {0} to {1}.
    /// </summary>
    internal static string Import_Chunked_ChunkDateRange {
        get {
            return ResourceManager.GetString("Import_Chunked_ChunkDateRange", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Completed in {0}.
    /// </summary>
    internal static string Import_Chunked_CompletedDuration {
        get {
            return ResourceManager.GetString("Import_Chunked_CompletedDuration", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Completed: {0} movements in {1} chunks.
    /// </summary>
    internal static string Import_Chunked_CompletedSummary {
        get {
            return ResourceManager.GetString("Import_Chunked_CompletedSummary", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Extracting {0}....
    /// </summary>
    internal static string Import_Chunked_ExtractingFile {
        get {
            return ResourceManager.GetString("Import_Chunked_ExtractingFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Extracting {0}... {1:F0}%.
    /// </summary>
    internal static string Import_Chunked_ExtractingFileWithProgress {
        get {
            return ResourceManager.GetString("Import_Chunked_ExtractingFileWithProgress", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import failed: {0}.
    /// </summary>
    internal static string Import_Chunked_Failed {
        get {
            return ResourceManager.GetString("Import_Chunked_Failed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing chunk {0} of {1}.
    /// </summary>
    internal static string Import_Chunked_ProcessingChunk {
        get {
            return ResourceManager.GetString("Import_Chunked_ProcessingChunk", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Reading {0}....
    /// </summary>
    internal static string Import_Chunked_ReadingFile {
        get {
            return ResourceManager.GetString("Import_Chunked_ReadingFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Analyzing dates.
    /// </summary>
    internal static string Import_Chunked_State_AnalyzingDates {
        get {
            return ResourceManager.GetString("Import_Chunked_State_AnalyzingDates", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating snapshots.
    /// </summary>
    internal static string Import_Chunked_State_CalculatingSnapshots {
        get {
            return ResourceManager.GetString("Import_Chunked_State_CalculatingSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import cancelled.
    /// </summary>
    internal static string Import_Chunked_State_Cancelled {
        get {
            return ResourceManager.GetString("Import_Chunked_State_Cancelled", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import completed.
    /// </summary>
    internal static string Import_Chunked_State_Completed {
        get {
            return ResourceManager.GetString("Import_Chunked_State_Completed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import failed.
    /// </summary>
    internal static string Import_Chunked_State_Failed {
        get {
            return ResourceManager.GetString("Import_Chunked_State_Failed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ready.
    /// </summary>
    internal static string Import_Chunked_State_Idle {
        get {
            return ResourceManager.GetString("Import_Chunked_State_Idle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing data.
    /// </summary>
    internal static string Import_Chunked_State_ProcessingChunk {
        get {
            return ResourceManager.GetString("Import_Chunked_State_ProcessingChunk", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Reading file.
    /// </summary>
    internal static string Import_Chunked_State_ReadingFile {
        get {
            return ResourceManager.GetString("Import_Chunked_State_ReadingFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to About {0} remaining.
    /// </summary>
    internal static string Import_Chunked_TimeRemaining {
        get {
            return ResourceManager.GetString("Import_Chunked_TimeRemaining", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Validating....
    /// </summary>
    internal static string Import_Chunked_Validating {
        get {
            return ResourceManager.GetString("Import_Chunked_Validating", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Validating {0}....
    /// </summary>
    internal static string Import_Chunked_ValidatingFile {
        get {
            return ResourceManager.GetString("Import_Chunked_ValidatingFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import completed successfully.
    /// </summary>
    internal static string Import_Completed {
        get {
            return ResourceManager.GetString("Import_Completed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Import failed.
    /// </summary>
    internal static string Import_Failed {
        get {
            return ResourceManager.GetString("Import_Failed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating broker snapshots.
    /// </summary>
    internal static string Import_Phase_CalculatingBrokerSnapshots {
        get {
            return ResourceManager.GetString("Import_Phase_CalculatingBrokerSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calculating ticker snapshots.
    /// </summary>
    internal static string Import_Phase_CalculatingTickerSnapshots {
        get {
            return ResourceManager.GetString("Import_Phase_CalculatingTickerSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Creating operations.
    /// </summary>
    internal static string Import_Phase_CreatingOperations {
        get {
            return ResourceManager.GetString("Import_Phase_CreatingOperations", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Loading movements.
    /// </summary>
    internal static string Import_Phase_LoadingMovements {
        get {
            return ResourceManager.GetString("Import_Phase_LoadingMovements", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saving data.
    /// </summary>
    internal static string Import_Phase_PersistingData {
        get {
            return ResourceManager.GetString("Import_Phase_PersistingData", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing {0}.
    /// </summary>
    internal static string Import_ProcessingFile {
        get {
            return ResourceManager.GetString("Import_ProcessingFile", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing file....
    /// </summary>
    internal static string Import_ProcessingFile_Generic {
        get {
            return ResourceManager.GetString("Import_ProcessingFile_Generic", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing {0} of {1} records.
    /// </summary>
    internal static string Import_ProcessingRecords {
        get {
            return ResourceManager.GetString("Import_ProcessingRecords", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Processing data....
    /// </summary>
    internal static string Import_ProcessingRecords_Generic {
        get {
            return ResourceManager.GetString("Import_ProcessingRecords_Generic", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saving {0} of {1} records.
    /// </summary>
    internal static string Import_SavingData {
        get {
            return ResourceManager.GetString("Import_SavingData", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Saving to database....
    /// </summary>
    internal static string Import_SavingData_Generic {
        get {
            return ResourceManager.GetString("Import_SavingData_Generic", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Broker Financial.
    /// </summary>
    internal static string Import_SnapshotType_BrokerFinancial {
        get {
            return ResourceManager.GetString("Import_SnapshotType_BrokerFinancial", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to broker snapshot.
    /// </summary>
    internal static string Import_SnapshotType_FinalBrokerSnapshots {
        get {
            return ResourceManager.GetString("Import_SnapshotType_FinalBrokerSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ticker snapshot.
    /// </summary>
    internal static string Import_SnapshotType_FinalTickerSnapshots {
        get {
            return ResourceManager.GetString("Import_SnapshotType_FinalTickerSnapshots", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Operations.
    /// </summary>
    internal static string Import_SnapshotType_Operations {
        get {
            return ResourceManager.GetString("Import_SnapshotType_Operations", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ticker Currency.
    /// </summary>
    internal static string Import_SnapshotType_TickerCurrency {
        get {
            return ResourceManager.GetString("Import_SnapshotType_TickerCurrency", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Validating file....
    /// </summary>
    internal static string Import_Validating {
        get {
            return ResourceManager.GetString("Import_Validating", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # Important   When creating a bank, you can use any name or identifier....
    /// </summary>
    internal static string Information_Create_Bank {
        get {
            return ResourceManager.GetString("Information_Create_Bank", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # Important  When creating a bank account, you should know that it is ....
    /// </summary>
    internal static string Information_Create_Bank_Account {
        get {
            return ResourceManager.GetString("Information_Create_Bank_Account", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # Important   When creating a broker, you can use any name or identifi....
    /// </summary>
    internal static string Information_Create_Broker {
        get {
            return ResourceManager.GetString("Information_Create_Broker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # Important  For the broker account, you can use any name or number yo....
    /// </summary>
    internal static string Information_Create_Broker_Account {
        get {
            return ResourceManager.GetString("Information_Create_Broker_Account", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # WARNING: High Risk of Leveraged Trading  Leveraged trading involves ....
    /// </summary>
    internal static string Information_Leveraged_Trading {
        get {
            return ResourceManager.GetString("Information_Leveraged_Trading", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to # Options Trading Basics  ## Option Types  ### CALL Options A CALL opt....
    /// </summary>
    internal static string Information_Options_Trading {
        get {
            return ResourceManager.GetString("Information_Options_Trading", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Change selection:.
    /// </summary>
    internal static string ItemSelector_Change_Selection {
        get {
            return ResourceManager.GetString("ItemSelector_Change_Selection", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Select an option:.
    /// </summary>
    internal static string ItemSelector_Select_Option {
        get {
            return ResourceManager.GetString("ItemSelector_Select_Option", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Leveraged.
    /// </summary>
    internal static string Leverage_Title {
        get {
            return ResourceManager.GetString("Leverage_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Movement type.
    /// </summary>
    internal static string MovementCreator_Type {
        get {
            return ResourceManager.GetString("MovementCreator_Type", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to How much &amp; when.
    /// </summary>
    internal static string MovementDepositControl_Title {
        get {
            return ResourceManager.GetString("MovementDepositControl_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ACAT Money Transfer Received.
    /// </summary>
    internal static string MovementType_ACATMoneyTransferReceived {
        get {
            return ResourceManager.GetString("MovementType_ACATMoneyTransferReceived", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Money received.
    /// </summary>
    internal static string MovementType_ACATMoneyTransferReceived_Subtitle {
        get {
            return ResourceManager.GetString("MovementType_ACATMoneyTransferReceived_Subtitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ACAT Money Transfer Sent.
    /// </summary>
    internal static string MovementType_ACATMoneyTransferSent {
        get {
            return ResourceManager.GetString("MovementType_ACATMoneyTransferSent", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Money sent.
    /// </summary>
    internal static string MovementType_ACATMoneyTransferSent_Subtitle {
        get {
            return ResourceManager.GetString("MovementType_ACATMoneyTransferSent_Subtitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ACAT Securities Transfer Received.
    /// </summary>
    internal static string MovementType_ACATSecuritiesTransferReceived {
        get {
            return ResourceManager.GetString("MovementType_ACATSecuritiesTransferReceived", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Securities received.
    /// </summary>
    internal static string MovementType_ACATSecuritiesTransferReceived_Subtitle {
        get {
            return ResourceManager.GetString("MovementType_ACATSecuritiesTransferReceived_Subtitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ACAT Securities Transfer Sent.
    /// </summary>
    internal static string MovementType_ACATSecuritiesTransferSent {
        get {
            return ResourceManager.GetString("MovementType_ACATSecuritiesTransferSent", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Securities sent.
    /// </summary>
    internal static string MovementType_ACATSecuritiesTransferSent_Subtitle {
        get {
            return ResourceManager.GetString("MovementType_ACATSecuritiesTransferSent_Subtitle", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ACAT Transfer.
    /// </summary>
    internal static string MovementType_ACATTransfer {
        get {
            return ResourceManager.GetString("MovementType_ACATTransfer", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Balance change.
    /// </summary>
    internal static string MovementType_Bank_Balance {
        get {
            return ResourceManager.GetString("MovementType_Bank_Balance", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fees.
    /// </summary>
    internal static string MovementType_Bank_Fees {
        get {
            return ResourceManager.GetString("MovementType_Bank_Fees", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Interests.
    /// </summary>
    internal static string MovementType_Bank_Interest {
        get {
            return ResourceManager.GetString("MovementType_Bank_Interest", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Conversion.
    /// </summary>
    internal static string MovementType_Conversion {
        get {
            return ResourceManager.GetString("MovementType_Conversion", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Deposit.
    /// </summary>
    internal static string MovementType_Deposit {
        get {
            return ResourceManager.GetString("MovementType_Deposit", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dividend Ex-Date.
    /// </summary>
    internal static string MovementType_DividendExDate {
        get {
            return ResourceManager.GetString("MovementType_DividendExDate", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dividend Payment Date.
    /// </summary>
    internal static string MovementType_DividendPayDate {
        get {
            return ResourceManager.GetString("MovementType_DividendPayDate", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dividend Received.
    /// </summary>
    internal static string MovementType_DividendReceived {
        get {
            return ResourceManager.GetString("MovementType_DividendReceived", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dividend Tax Withheld.
    /// </summary>
    internal static string MovementType_DividendTaxWithheld {
        get {
            return ResourceManager.GetString("MovementType_DividendTaxWithheld", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fee.
    /// </summary>
    internal static string MovementType_Fee {
        get {
            return ResourceManager.GetString("MovementType_Fee", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Interests gained.
    /// </summary>
    internal static string MovementType_InterestsGained {
        get {
            return ResourceManager.GetString("MovementType_InterestsGained", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Interests paid.
    /// </summary>
    internal static string MovementType_InterestsPaid {
        get {
            return ResourceManager.GetString("MovementType_InterestsPaid", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gained for lending.
    /// </summary>
    internal static string MovementType_Lending {
        get {
            return ResourceManager.GetString("MovementType_Lending", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Option Trade.
    /// </summary>
    internal static string MovementType_OptionTrade {
        get {
            return ResourceManager.GetString("MovementType_OptionTrade", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Trade.
    /// </summary>
    internal static string MovementType_Trade {
        get {
            return ResourceManager.GetString("MovementType_Trade", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Withdrawal.
    /// </summary>
    internal static string MovementType_Withdrawal {
        get {
            return ResourceManager.GetString("MovementType_Withdrawal", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Buy to close.
    /// </summary>
    internal static string Movement_BuyToClose {
        get {
            return ResourceManager.GetString("Movement_BuyToClose", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Buy to open.
    /// </summary>
    internal static string Movement_BuyToOpen {
        get {
            return ResourceManager.GetString("Movement_BuyToOpen", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sell to close.
    /// </summary>
    internal static string Movement_SellToClose {
        get {
            return ResourceManager.GetString("Movement_SellToClose", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sell to open.
    /// </summary>
    internal static string Movement_SellToOpen {
        get {
            return ResourceManager.GetString("Movement_SellToOpen", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Multiplier.
    /// </summary>
    internal static string Multiplier_Title {
        get {
            return ResourceManager.GetString("Multiplier_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Assigned.
    /// </summary>
    internal static string OptionCode_Assigned {
        get {
            return ResourceManager.GetString("OptionCode_Assigned", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Assigned.
    /// </summary>
    internal static string OptionCode_Assigned_Extended {
        get {
            return ResourceManager.GetString("OptionCode_Assigned_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to BTC.
    /// </summary>
    internal static string OptionCode_BTC {
        get {
            return ResourceManager.GetString("OptionCode_BTC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Buy to close.
    /// </summary>
    internal static string OptionCode_BTC_Extended {
        get {
            return ResourceManager.GetString("OptionCode_BTC_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to BTO.
    /// </summary>
    internal static string OptionCode_BTO {
        get {
            return ResourceManager.GetString("OptionCode_BTO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Buy to open.
    /// </summary>
    internal static string OptionCode_BTO_Extended {
        get {
            return ResourceManager.GetString("OptionCode_BTO_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cash Settled Assigned.
    /// </summary>
    internal static string OptionCode_CashSettledAssigned {
        get {
            return ResourceManager.GetString("OptionCode_CashSettledAssigned", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cash Settled Exercised.
    /// </summary>
    internal static string OptionCode_CashSettledExercised {
        get {
            return ResourceManager.GetString("OptionCode_CashSettledExercised", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Exercised.
    /// </summary>
    internal static string OptionCode_Exercised {
        get {
            return ResourceManager.GetString("OptionCode_Exercised", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Expired.
    /// </summary>
    internal static string OptionCode_Expired {
        get {
            return ResourceManager.GetString("OptionCode_Expired", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Expired.
    /// </summary>
    internal static string OptionCode_Expired_Extended {
        get {
            return ResourceManager.GetString("OptionCode_Expired_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to STC.
    /// </summary>
    internal static string OptionCode_STC {
        get {
            return ResourceManager.GetString("OptionCode_STC", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sell to close.
    /// </summary>
    internal static string OptionCode_STC_Extended {
        get {
            return ResourceManager.GetString("OptionCode_STC_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to STO.
    /// </summary>
    internal static string OptionCode_STO {
        get {
            return ResourceManager.GetString("OptionCode_STO", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sell to open.
    /// </summary>
    internal static string OptionCode_STO_Extended {
        get {
            return ResourceManager.GetString("OptionCode_STO_Extended", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Option code:.
    /// </summary>
    internal static string OptionCode_Title {
        get {
            return ResourceManager.GetString("OptionCode_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to CALL.
    /// </summary>
    internal static string OptionType_Call {
        get {
            return ResourceManager.GetString("OptionType_Call", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to PUT.
    /// </summary>
    internal static string OptionType_Put {
        get {
            return ResourceManager.GetString("OptionType_Put", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Option type:.
    /// </summary>
    internal static string OptionType_Title {
        get {
            return ResourceManager.GetString("OptionType_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Start creating an account for a broker or bank to start your binnacle..
    /// </summary>
    internal static string Overview_Empty_Account_Info {
        get {
            return ResourceManager.GetString("Overview_Empty_Account_Info", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Movements will appear here once they are added to your account..
    /// </summary>
    internal static string Overview_No_Movements {
        get {
            return ResourceManager.GetString("Overview_No_Movements", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to My accounts.
    /// </summary>
    internal static string Overview_Title {
        get {
            return ResourceManager.GetString("Overview_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Type the amount.
    /// </summary>
    internal static string Placeholder_Amount {
        get {
            return ResourceManager.GetString("Placeholder_Amount", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Commissions.
    /// </summary>
    internal static string Placeholder_Commissions {
        get {
            return ResourceManager.GetString("Placeholder_Commissions", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Converting.
    /// </summary>
    internal static string Placeholder_Conversion_From {
        get {
            return ResourceManager.GetString("Placeholder_Conversion_From", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Converted.
    /// </summary>
    internal static string Placeholder_Conversion_To {
        get {
            return ResourceManager.GetString("Placeholder_Conversion_To", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Fees.
    /// </summary>
    internal static string Placeholder_Fees {
        get {
            return ResourceManager.GetString("Placeholder_Fees", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Type a note.
    /// </summary>
    internal static string Placeholder_Note {
        get {
            return ResourceManager.GetString("Placeholder_Note", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Price.
    /// </summary>
    internal static string Placeholder_Price {
        get {
            return ResourceManager.GetString("Placeholder_Price", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Quantity.
    /// </summary>
    internal static string Placeholder_Quantity {
        get {
            return ResourceManager.GetString("Placeholder_Quantity", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Search ticker.
    /// </summary>
    internal static string Placeholder_Search_ticker {
        get {
            return ResourceManager.GetString("Placeholder_Search_ticker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Type the ticker name.
    /// </summary>
    internal static string Placeholder_Type_Ticker_Name {
        get {
            return ResourceManager.GetString("Placeholder_Type_Ticker_Name", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Type the ticker symbol.
    /// </summary>
    internal static string Placeholder_Type_Ticker_Symbol {
        get {
            return ResourceManager.GetString("Placeholder_Type_Ticker_Symbol", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Delete all data.
    /// </summary>
    internal static string Settings_DeleteAllData_Button {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Button", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Failed to delete data: {0}.
    /// </summary>
    internal static string Settings_DeleteAllData_Error_Message {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Error_Message", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to This will permanently delete all your operations, accounts, movements,....
    /// </summary>
    internal static string Settings_DeleteAllData_Message {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Message", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Are you absolutely sure? This is your last chance to cancel..
    /// </summary>
    internal static string Settings_DeleteAllData_SecondConfirm_Message {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_SecondConfirm_Message", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Final Confirmation.
    /// </summary>
    internal static string Settings_DeleteAllData_SecondConfirm_Title {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_SecondConfirm_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to All operational data has been deleted successfully..
    /// </summary>
    internal static string Settings_DeleteAllData_Success_Message {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Success_Message", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Delete All Data.
    /// </summary>
    internal static string Settings_DeleteAllData_Title {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to ⚠️ This action cannot be undone!.
    /// </summary>
    internal static string Settings_DeleteAllData_Warning {
        get {
            return ResourceManager.GetString("Settings_DeleteAllData_Warning", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Allow create accounts.
    /// </summary>
    internal static string Settings_Section_General_Allow_Create_Account {
        get {
            return ResourceManager.GetString("Settings_Section_General_Allow_Create_Account", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Currency.
    /// </summary>
    internal static string Settings_Section_General_Currency {
        get {
            return ResourceManager.GetString("Settings_Section_General_Currency", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Group options.
    /// </summary>
    internal static string Settings_Section_General_Group_Option_Trades {
        get {
            return ResourceManager.GetString("Settings_Section_General_Group_Option_Trades", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ticker.
    /// </summary>
    internal static string Settings_Section_General_Ticker {
        get {
            return ResourceManager.GetString("Settings_Section_General_Ticker", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to General.
    /// </summary>
    internal static string Settings_Section_General_Title {
        get {
            return ResourceManager.GetString("Settings_Section_General_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to [Report a problem or improvement.](https://github.com/DarioAlonsoCerez....
    /// </summary>
    internal static string Settings_Section_Issue {
        get {
            return ResourceManager.GetString("Settings_Section_Issue", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to English.
    /// </summary>
    internal static string Settings_Section_Language_English {
        get {
            return ResourceManager.GetString("Settings_Section_Language_English", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Spanish.
    /// </summary>
    internal static string Settings_Section_Language_Spanish {
        get {
            return ResourceManager.GetString("Settings_Section_Language_Spanish", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Language setting.
    /// </summary>
    internal static string Settings_Section_Language_Title {
        get {
            return ResourceManager.GetString("Settings_Section_Language_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Dark.
    /// </summary>
    internal static string Settings_Section_Theme_Dark {
        get {
            return ResourceManager.GetString("Settings_Section_Theme_Dark", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Device.
    /// </summary>
    internal static string Settings_Section_Theme_Device {
        get {
            return ResourceManager.GetString("Settings_Section_Theme_Device", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Light.
    /// </summary>
    internal static string Settings_Section_Theme_Light {
        get {
            return ResourceManager.GetString("Settings_Section_Theme_Light", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Theme setting.
    /// </summary>
    internal static string Settings_Section_Theme_Title {
        get {
            return ResourceManager.GetString("Settings_Section_Theme_Title", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Calendar.
    /// </summary>
    internal static string Shell_Tab_Calendar {
        get {
            return ResourceManager.GetString("Shell_Tab_Calendar", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Overview.
    /// </summary>
    internal static string Shell_Tab_Overview {
        get {
            return ResourceManager.GetString("Shell_Tab_Overview", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    internal static string Shell_Tab_Settings {
        get {
            return ResourceManager.GetString("Shell_Tab_Settings", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Strategies.
    /// </summary>
    internal static string Shell_Tab_Strategies {
        get {
            return ResourceManager.GetString("Shell_Tab_Strategies", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tickers.
    /// </summary>
    internal static string Shell_Tab_Tickers {
        get {
            return ResourceManager.GetString("Shell_Tab_Tickers", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} hours.
    /// </summary>
    internal static string Time_Format_Hours {
        get {
            return ResourceManager.GetString("Time_Format_Hours", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to less than a minute.
    /// </summary>
    internal static string Time_Format_LessThanMinute {
        get {
            return ResourceManager.GetString("Time_Format_LessThanMinute", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} minutes.
    /// </summary>
    internal static string Time_Format_Minutes {
        get {
            return ResourceManager.GetString("Time_Format_Minutes", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to {0} seconds.
    /// </summary>
    internal static string Time_Format_Seconds {
        get {
            return ResourceManager.GetString("Time_Format_Seconds", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Today.
    /// </summary>
    internal static string Today {
        get {
            return ResourceManager.GetString("Today", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to Yesterday.
    /// </summary>
    internal static string Yesterday {
        get {
            return ResourceManager.GetString("Yesterday", resourceCulture);
        }
    }

}

___BEGIN___COMMAND_DONE_MARKER___0
